name = "aiken-lang/104"
version = "0.0.0"
compiler = "v1.0.29-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/104'"

[repository]
user = "aiken-lang"
project = "104"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "main"
source = "github"
