name = "paas/validate_signature"
version = "0.0.0"
author = "Thang Tran"
compiler = "v1.1.23"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'paas/validate_signature'"

[repository]
user = "paas"
project = "validate_signature"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"
