name = "aiken-lang/validate_signature"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "Aiken contracts for project 'aiken-lang/validate_signature'"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
