name = "aiken-lang/validate_signature_message"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'paas'"

[repository]
user = "aiken-lang"
project = "paas"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
